# Generated by Django 5.0.2 on 2024-03-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0003_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_country', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('short_sleeve', models.BooleanField()),
                ('status', models.BooleanField()),
                ('player', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
